version: '3'
services:
  flask:
    build: ./backend
    container_name: backend-flask
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=True                   
    restart: on-failure
    volumes:
      - ./:/backend
    ports:
      - "5000:5000"
    command: python app.py